export const ADD = 'ADD'
export const EDIT = 'EDIT'

export const ADD_CATEGORY = 'ADD_CATEGORY'
export const REMOVE_CATEGORY = 'REMOVE_CATEGORY'
export const EDIT_CATEGORY = 'EDIT_CATEGORY'
export const GET_CATEGORY_LIST = 'GET_CATEGORY_LIST'
export const ERR_CATEGORY = 'ERR_CATEGORY'
export const START_LOADING_CATS = 'START_LOADING_CATS'