/* Константы для навигации */
export const TARGET = 1
export const IDEBT = 2
export const OWEME = 3
export const EDIT = 0
/* Константы для редьюсеров */
export const GET_TARGET_LIST = 'GET_TARGET_LIST'
export const REMOVE_TARGET = 'REMOVE_TARGET'
export const ADD_TARGET = 'ADD_TARGET'
export const EDIT_TARGET = 'EDIT_TARGET'
export const ERR_TARGET = 'ERR_TARGET'
export const INCREASE_TARGET = 'INCREASE_TARGET'
export const START_LOADING_TARGET = 'START_LOADING_TARGET'